"""
Static item definitions for Cash cleaner simulator (ccs).
"""
from __future__ import annotations
from typing import Dict
from BaseClasses import ItemClassification

item_name_to_id = {
    "More quest money packs": 0xCE0500,
    "More container density": 0xCE0502,
    "Less marked money": 0xCE0504,
    "Less required money": 0xCE0506,
    "Less trash": 0xCE050A,
    "Less currency mix": 0xCE050C,
    "More rare money": 0xCE050E,
    "More quest money": 0xCE0510,
    "Stack Size Upgrade": 0xCE0512,
    "Reputation": 0xCE0516,
    "Cryptocurrency": 0xCE0541,
    "Reduced Money gun requirement": 0xCE054A,
    "Reduced Washer requirement": 0xCE054B,
    "Reduced UV Lamp requirement": 0xCE054C,
    "Reduced Dryer requirement": 0xCE054D,
    "Reduced Money counter requirement": 0xCE054E,
    "Reduced Money counter tier 2 requirement": 0xCE054F,
    "Reduced Euro Money counter tier 2 requirement": 0xCE0550,
    "Reduced Yen Money counter tier 2 requirement": 0xCE0551,
    "Reduced Money counter tier 3 requirement": 0xCE0552,
    "Reduced Ladder requirement": 0xCE0553,
    "Reduced Sponge requirement": 0xCE0554,
    "Reduced Marked money Counter requirement": 0xCE0555,
    "Reduced Workbench Ink Foam requirement": 0xCE0556,
    "Reduced Workbench Mark Foam requirement": 0xCE0557,
    "Reduced Workbench Goo Foam requirement": 0xCE0558,
    "Reduced Ink detergent requirement": 0xCE0559,
    "Reduced Mark detergent requirement": 0xCE055A,
    "Reduced Goo detergent requirement": 0xCE055B,
    "Reduced Big Washer requirement": 0xCE055C,
    "Reduced Sticker gun requirement": 0xCE055D,
    "Reduced Coin counter requirement": 0xCE055E,
    # Traps
    "Random Trash Trap": 0xCE0600,
    "Random Wet Trap": 0xCE0601,
    "Random Dirty Trap": 0xCE0602,
    "Random Inked Trap": 0xCE0603,
    "Random Goo? Trap": 0xCE0604,
}

item_name_to_count = {
    "More quest money packs": 2,
    "More container density": 2,
    "Less marked money": 2,
    "Less required money": 4,
    "Less trash": 2,
    "Less currency mix": 2,
    "More rare money": 2,
    "More quest money": 2,
    "Stack Size Upgrade": 4,
    "Reputation": 43,
    "Cryptocurrency": 9,
    "Reduced Money gun requirement": 3,
    "Reduced Washer requirement": 3,
    "Reduced UV Lamp requirement": 3,
    "Reduced Dryer requirement": 3,
    "Reduced Money counter requirement": 3,
    "Reduced Money counter tier 2 requirement": 3,
    "Reduced Euro Money counter tier 2 requirement": 3,
    "Reduced Yen Money counter tier 2 requirement": 3,
    "Reduced Money counter tier 3 requirement": 3,
    "Reduced Ladder requirement": 3,
    "Reduced Sponge requirement": 3,
    "Reduced Marked money Counter requirement": 3,
    "Reduced Workbench Ink Foam requirement": 3,
    "Reduced Workbench Mark Foam requirement": 3,
    "Reduced Workbench Goo Foam requirement": 3,
    "Reduced Ink detergent requirement": 3,
    "Reduced Mark detergent requirement": 3,
    "Reduced Goo detergent requirement": 3,
    "Reduced Big Washer requirement": 3,
    "Reduced Sticker gun requirement": 3,
    "Reduced Coin counter requirement": 3,
    # Traps
    "Random Trash Trap": 0,
    "Random Wet Trap": 0,
    "Random Dirty Trap": 0,
    "Random Inked Trap": 0,
    "Random Goo? Trap": 0,
}

item_name_to_classification = {
    "More quest money packs": ItemClassification.useful,
    "More container density": ItemClassification.useful,
    "Less marked money": ItemClassification.useful,
    "Less required money": ItemClassification.useful,
    "Less trash": ItemClassification.useful,
    "Less currency mix": ItemClassification.useful,
    "More rare money": ItemClassification.useful,
    "More quest money": ItemClassification.useful,
    "Stack Size Upgrade": ItemClassification.progression,
    "Reputation": ItemClassification.progression, 
    "Cryptocurrency": ItemClassification.filler,
    "Reduced Money gun requirement": ItemClassification.progression,
    "Reduced Washer requirement": ItemClassification.progression,
    "Reduced UV Lamp requirement": ItemClassification.useful,
    "Reduced Dryer requirement": ItemClassification.progression,
    "Reduced Money counter requirement": ItemClassification.progression,
    "Reduced Money counter tier 2 requirement": ItemClassification.useful,
    "Reduced Euro Money counter tier 2 requirement": ItemClassification.progression,
    "Reduced Yen Money counter tier 2 requirement": ItemClassification.progression,
    "Reduced Money counter tier 3 requirement": ItemClassification.useful,
    "Reduced Ladder requirement": ItemClassification.progression,
    "Reduced Sponge requirement": ItemClassification.useful,
    "Reduced Marked money Counter requirement": ItemClassification.progression,
    "Reduced Workbench Ink Foam requirement": ItemClassification.useful,
    "Reduced Workbench Mark Foam requirement": ItemClassification.useful,
    "Reduced Workbench Goo Foam requirement": ItemClassification.useful,
    "Reduced Ink detergent requirement": ItemClassification.useful,
    "Reduced Mark detergent requirement": ItemClassification.useful,
    "Reduced Goo detergent requirement": ItemClassification.useful,
    "Reduced Big Washer requirement": ItemClassification.progression,
    "Reduced Sticker gun requirement": ItemClassification.progression,
    "Reduced Coin counter requirement": ItemClassification.useful,
    # Traps
    "Random Trash Trap": ItemClassification.trap,
    "Random Wet Trap": ItemClassification.trap,
    "Random Dirty Trap": ItemClassification.trap,
    "Random Inked Trap": ItemClassification.trap,
    "Random Goo? Trap": ItemClassification.trap,
}