"""Static location definitions for Cash cleaner simulator (ccs).
"""
from __future__ import annotations

from typing import Dict


# Single static mapping for locations (addresses chosen sequentially from 0xCE0000)
location_name_to_id: Dict[str, int] = {
    # MainQuests
    "Main Quest Tutorial: Controls Movement":       0xCE0000,
    "Main Quest Tutorial: Controls Interactions":   0xCE0001,
    "Main Quest Tutorial: Smartphone":              0xCE0002,
    "Main Quest Tutorial: Manipulation":            0xCE0003,
    "Main Quest Tutorial: Conveyor":                0xCE0004,
    "Main Quest Side: The Call Of Cash":            0xCE0005,
    "Main Quest Tutorial: Take Quest":              0xCE0006,
    "Main Quest Tutorial: Task Tracker":            0xCE0007,
    "Main Quest Tutorial: Finish Quest":            0xCE0008,
    "Main Quest Main: Clean It Or Skip It":         0xCE0009,
    "Main Quest Main: Shop Till It Drops":          0xCE000A,
    "Main Quest Side: The Wet Case":                0xCE000B,
    "Main Quest Side: Fifty Shades Of Cash":        0xCE000C,
    "Main Quest Side: Hot Dry":                     0xCE000D,
    "Main Quest Side: Clean Cut":                   0xCE000E,
    "Main Quest Side: Two Cases":                   0xCE000F,
    "Main Quest Side: From Chaos To Cash":          0xCE0010,
    "Main Quest Side: Silent Deal":                 0xCE0011,
    "Main Quest Side: Fake Fluff":                  0xCE0012,
    "Main Quest Side: No Stains":                   0xCE0013,
    "Main Quest Main: Cleansing Fire":              0xCE0014,
    "Main Quest Main: The Light Test":              0xCE0015,
    "Main Quest Side: Light It Up":                 0xCE0016,
    "Main Quest Main: Feed The Pig":                0xCE0017,
    "Main Quest Side: Different Values":            0xCE0018,
    "Main Quest Main: Europhoria":                  0xCE0019,
    "Main Quest Main: Blacklight Evidence":         0xCE001A,
    "Main Quest Main: Pre Launch Protocol":         0xCE001B,
    "Main Quest Main: Saving Piglet":               0xCE001C,
    "Main Quest Side: Luxury Wrapping":             0xCE001D,
    "Main Quest Main: Golden Cage Breakout":        0xCE001E,
    "Main Quest Side: Fragile Treasure":            0xCE001F,
    "Main Quest Side: Financial Exorcism":          0xCE0020,
    "Main Quest Side: What They Left Behind":       0xCE0021,
    "Main Quest Side: Financial Zoo":               0xCE0022,
    "Main Quest Side: Tracing The Bullet":          0xCE0023,
    "Main Quest Side: Collectors Edition":          0xCE0024,
    "Main Quest Side: The Money Flow":              0xCE0025,
    "Main Quest Side: The Magician Choice":         0xCE0026,
    "Main Quest Side: Ocean Of Emojis":             0xCE0027,
    "Main Quest Side: Lawful Goo":                  0xCE0028,
    "Main Quest Side: Mind Your Business":          0xCE0029,
    "Main Quest Main: The Vault Of Truth":          0xCE002A,
    "Main Quest Main: Operation Black File":        0xCE002B,
    "Main Quest Side: Combo Heist":                 0xCE002C,
    "Main Quest Main: Launch Code OINK":            0xCE002D,
    "Main Quest Main: Inflation Sequence":          0xCE002E,
    "Main Quest Main: Priming The Shot":            0xCE002F,
    "Main Quest Main: Loaded But Undecided":        0xCE0030,
    "Main Quest Side: Acid Conspiracy":             0xCE0031,
    "Main Quest Main: Final Ascent":                0xCE0032,
    "Main Quest Main: Point Of No Return":          0xCE0033,
    # Side quests
    "SideQuest 1":                                  0xCE0034,
    "SideQuest 2":                                  0xCE0035,
    "SideQuest 3":                                  0xCE0036,
    "SideQuest 4":                                  0xCE0037,
    "SideQuest 5":                                  0xCE0038,
    "SideQuest 6":                                  0xCE0039,
    "SideQuest 7":                                  0xCE003A,
    "SideQuest 8":                                  0xCE003B,
    "SideQuest 9":                                  0xCE003C,
    "SideQuest 10":                                 0xCE003D,
    "SideQuest 11":                                 0xCE003E,
    "SideQuest 12":                                 0xCE003F,
    "SideQuest 13":                                 0xCE0040,
    "SideQuest 14":                                 0xCE0041,
    "SideQuest 15":                                 0xCE0042,
    "SideQuest 16":                                 0xCE0043,
    "SideQuest 17":                                 0xCE0044,
    "SideQuest 18":                                 0xCE0045,
    "SideQuest 19":                                 0xCE0046,
    "SideQuest 20":                                 0xCE0047,
    "SideQuest 21":                                 0xCE0048,
    "SideQuest 22":                                 0xCE0049,
    "SideQuest 23":                                 0xCE004A,
    "SideQuest 24":                                 0xCE004B,
    "SideQuest 25":                                 0xCE004C,
    "SideQuest 26":                                 0xCE004D,
    "SideQuest 27":                                 0xCE004E,
    "SideQuest 28":                                 0xCE004F,
    "SideQuest 29":                                 0xCE0050,
    "SideQuest 30":                                 0xCE0051,
    # Side quests bonus
    "Quest Bonus: Exact money value":               0xCE0052,
    "Quest Bonus: More money value":                0xCE0053,
    "Quest Bonus: Much more money value":           0xCE0054,
    "Quest Bonus: Single delivery":                 0xCE0055,
    "Quest Bonus: Nothing else":                    0xCE0056,
    "Quest Bonus: No marked money":                 0xCE0057,
    "Quest Bonus: No marked money specific quest":  0xCE0058,
    "Quest Bonus: No fake money":                   0xCE0059,
    "Quest Bonus: No fake money specific quest":    0xCE005A,
    "Quest Bonus: Perfect packs":                   0xCE005B,
    "Quest Bonus: Perfect packs specific quest":    0xCE005C,
    "Quest Bonus: Perfect blocks":                  0xCE005D,
    "Quest Bonus: Perfect blocks specific quest":   0xCE005E,
    "Quest Bonus: Marked with Labels!":             0xCE005F,
    "Quest Bonus: Perfect rolls":                   0xCE0060,
    "Quest Bonus: Perfect roll-blocks":             0xCE0061,
    # World interactions
    "Unlock relax area":                            0xCE0062,
    "Unlock upper area":                            0xCE0063,
    "Dunk!":                                        0xCE0064,
    "Rest out of bound":                            0xCE0065,
    "Buy a money gun":                              0xCE0066,
    "Marked bill collection: FBI":                  0xCE0067,
    "Marked bill collection: Police":               0xCE0068,
    "Marked bill collection: Yakuza":               0xCE0069,
    "Marked bill collection: Mafia":                0xCE006A,
    "Marked bill collection: Cartel":               0xCE006B,
    "Marked bill collection: Unknown":              0xCE006C,
    "Coin collection: Pitcoin":                     0xCE006D,
    "Coin collection: Legionnare":                  0xCE006E,
    "Coin collection: Liberty":                     0xCE006F,
    "Coin collection: Pirate":                      0xCE0070,
    "Coin collection: Ashoka Lion":                 0xCE0071,
    "Coin collection: Fugio":                       0xCE0072,
    "Coin collection: Edokoban":                    0xCE0073,
    "Coin collection: Retro Pixel":                 0xCE0074,
    "Art Bill collection: EUR 100":                 0xCE0075,
    "Art Bill collection: EUR 50":                  0xCE0076,
    "Art Bill collection: EUR 20":                  0xCE0077,
    "Art Bill collection: JPY 10000":               0xCE0078,
    "Art Bill collection: JPY 5000":                0xCE0079,
    "Art Bill collection: JPY 1000":                0xCE007A,
    "Art Bill collection: USD 100":                 0xCE007B,
    "Art Bill collection: USD 50":                  0xCE007C,
    "Art Bill collection: USD 20":                  0xCE007D,
    "Art Bill collection: USD 10":                  0xCE007E,
    # SideQuest Difficulty
    "Side quest Difficulty 0":                      0xCE007F,
    "Side quest Difficulty 1":                      0xCE0080,
    "Side quest Difficulty 2":                      0xCE0081,
    "Side quest Difficulty 3":                      0xCE0082,
    "Side quest Difficulty 4":                      0xCE0083,
    "Side quest Difficulty 5":                      0xCE0084,
    "Side quest Difficulty 6":                      0xCE0085,
    "Side quest Difficulty 7":                      0xCE0086,
    "Side quest Difficulty 8":                      0xCE0087,
    "Side quest Difficulty 9":                      0xCE0088,
}
